#
# Autogenerated by Thrift Compiler (0.9.1)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require_relative 'hello_service_types'

module HelloService
  class Client
    include ::Thrift::Client

    def say_hello(name)
      send_say_hello(name)
      return recv_say_hello()
    end

    def send_say_hello(name)
      send_message('say_hello', Say_hello_args, :name => name)
    end

    def recv_say_hello()
      result = receive_message(Say_hello_result)
      return result.success unless result.success.nil?
      raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'say_hello failed: unknown result')
    end

  end

  class Processor
    include ::Thrift::Processor

    def process_say_hello(seqid, iprot, oprot)
      args = read_args(iprot, Say_hello_args)
      result = Say_hello_result.new()
      result.success = @handler.say_hello(args.name)
      write_result(result, oprot, 'say_hello', seqid)
    end

  end

  # HELPER FUNCTIONS AND STRUCTURES

  class Say_hello_args
    include ::Thrift::Struct, ::Thrift::Struct_Union
    NAME = 1

    FIELDS = {
      NAME => {:type => ::Thrift::Types::STRING, :name => 'name'}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class Say_hello_result
    include ::Thrift::Struct, ::Thrift::Struct_Union
    SUCCESS = 0

    FIELDS = {
      SUCCESS => {:type => ::Thrift::Types::STRING, :name => 'success'}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

end

